### ISSUE TITLE
Error generating angular components

### ISSUE THREAD

**Issue by reshadf** [FountainJS/generator-fountain-webapp#158]
Hi I am new to angular. I try to create a controller but it results in a error everytime. 
For example 

    yo angular:controller login 

results in

    Unable to find app/index.html. Reference to controllers/login.js not added.

Has this something to do with my fountainjs setup or is it a known bug?

**Comment by sickpalmex** [comment]
Hi @reshadf: 

What generator and angular version do you use? I believe that angular generator is incompatible with generator-fountain-webapp since instead of creating a controller you create a component, if you created your project with `yo fountain-webapp` and you are using angular1 you must run `yo fountain-angular1: component --name login`, which will create the html template and the javascript file (which contains the controller).

I hope I have been helpful.

**Comment by micaelmbagira** [comment]
Right, the syntax is `yo fountain-angular1: component --name login`.
